# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u540d')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u54c1\u724c\u8868',
                'verbose_name_plural': '\u8bbe\u5907\u54c1\u724c\u8868',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices_id', models.CharField(max_length=20, verbose_name='\u8bbe\u5907ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u540d')),
                ('version', models.CharField(max_length=50, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('borrower', models.CharField(max_length=20, verbose_name='\u501f\u7528\u4eba')),
                ('status', models.CharField(default='True', max_length=16, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Brand', verbose_name='\u8bbe\u5907\u54c1\u724c')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u8bbe\u5907\u4fe1\u606f\u8868',
            },
        ),
    ]
