# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u54c1\u724c'),
        ),
    ]
