# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20170901_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('True', '\u672a\u501f\u7528'), ('False', '\u5df2\u501f\u7528'), ('Error', '\u8bbe\u5907\u5f02\u5e38')], default='True', max_length=16, verbose_name='\u8bbe\u5907\u72b6\u6001'),
        ),
    ]
