# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20170902_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '\u8bbe\u5907\u54c1\u724c', 'verbose_name_plural': '\u8bbe\u5907\u54c1\u724c'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '\u8bbe\u5907\u767b\u8bb0', 'verbose_name_plural': '\u8bbe\u5907\u767b\u8bb0'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u5c0f\u4f19\u4f34', 'verbose_name_plural': '\u5c0f\u4f19\u4f34'},
        ),
        migrations.AlterField(
            model_name='message',
            name='borrower',
            field=models.ForeignKey(blank=True, default='/', null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.UserProfile', verbose_name='\u501f\u7528\u4eba'),
        ),
    ]
