# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20170830_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('work_time', models.IntegerField(max_length=10, verbose_name='\u9884\u8ba1\u5de5\u65f6')),
                ('business_obj', models.CharField(max_length=20, verbose_name='\u4e1a\u52a1\u8ddf\u8e2a\u4eba')),
                ('test_time', models.IntegerField(max_length=10, verbose_name='\u6d4b\u8bd5\u65f6\u95f4')),
                ('comment', models.CharField(max_length=100, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u62a5\u8868',
                'verbose_name_plural': '\u4efb\u52a1\u62a5\u8868',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u7c7b\u578b')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u7c7b\u578b',
                'verbose_name_plural': '\u4efb\u52a1\u7c7b\u578b',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.UserProfile', verbose_name='\u501f\u7528\u4eba'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Types', verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='job',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.UserProfile', verbose_name='\u6d4b\u8bd5\u5de5\u7a0b\u5e08'),
        ),
    ]
