# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20170830_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
