# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_auto_20170831_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_report',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.UserProfile', verbose_name='\u6d4b\u8bd5\u5de5\u7a0b\u5e08'),
        ),
    ]
