# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_auto_20170831_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('men', '\u9177\u54e5'), ('woman', '\u9753\u5973')], default='woman', max_length=8, verbose_name='\u6027\u522b'),
        ),
    ]
