# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_auto_20170831_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
