# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_message_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='add_time',
        ),
        migrations.AddField(
            model_name='message',
            name='modify_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'2017,09,04 12:02:07'),
        ),
    ]
