# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20170904_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='modify_time',
            field=models.CharField(blank=True, default=b'2017,09,04 12:05:44', max_length=100, null=True, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
