# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_auto_20170904_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u501f\u7528\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='message',
            name='modify_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, max_length=100, null=True, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
