# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_auto_20170904_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, max_length=100, null=True, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='message',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u501f\u7528\u65f6\u95f4'),
        ),
    ]
